version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php-fpm.conf:/usr/local/php-fpm.d/php-fpm.conf
    environment:
      DATABASE_URL: mysql://my-user:my-user-password@mysql/wp-bedrock
      WP_ENV: production
      WP_HOME: http://localhost:3000
      WP_SITEURL: http://localhost:3000/wp
      AUTH_KEY: "{lmM6FX9:,NJ3l`igw]]35-%Swauw?FbyPXVQ)x=1?T4!-vAo`C*yq<[gvA0eDBY"
      SECURE_AUTH_KEY: "pC{]pvf)Me#Snx/AH7Q-,L|K`IM0c9C%]JTxSQCmzSo2/ckQ38EzL/73JRN4Sl?S"
      LOGGED_IN_KEY: "|29Ym(+in+dX342Y6:JF#Hd=:?19]ok9|l]C,QXVZggoD%/X6ALg`<[)SKPn3:98"
      NONCE_KEY: "kWGliB}RG(em}-,}!b}O[VIPmg:FjF^C&*|4;iO.}VxE{6JDTePe:652G1TND1F="
      AUTH_SALT: "?/WY)fGKhTU.;ML)MEX?9Hmzzy}HH!<+*NA(}JCw-v7qfO2YBqioY39NL?l1dLGI"
      SECURE_AUTH_SALT: "B%sK)A&`8WcV|-BwO>/r/vBYz:#@o8;k@;7SVxfr/Q0d7ain/Bc.|RDC?fJ77?zG"
      LOGGED_IN_SALT: "^)3gZJFH|TZYof9:L-u&G!mnB(FH[d)CQ.wY4A4Y?P|kii,EEv]yX)2XY8q4Te!c"
      NONCE_SALT: "W-7lds_*y*k4+%S)e{Bu{b4AgWEtsy8GJ#8uF-[&DG6<C#(ZOz0*[5JWqU?QmB[5"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: "azertyuiop"
      MYSQL_DATABASE: wp-bedrock
      MYSQL_USER: "my-user"
      MYSQL_PASSWORD: "my-user-password"
    volumes:
      - ./docker/mysql:/var/lib/mysql

  nginx:
    image: nginx:1
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - web

  composer:
    image: composer:1
    working_dir: /app
    restart: 'no'
    volumes:
      - .:/app
